import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import profilPic from "../assets/images/image.png";
import { ArrowCircleDownIcon, ArrowRightIcon } from "@heroicons/react/outline";
import Link from "next/link";
import { useState } from "react";
export default function Home() {
  const [buttonSate, setButtonState] = useState("hidden");
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-[#eee2dc] p-10">
        <h1 className="text-[34px] text-[#ac3b61] font-black pb-5 text-center">
          Abhinav Kumar
        </h1>
        <div className="w-[150px]  m-auto">
          <img src="https://media3.giphy.com/media/3oFzmokTcNdZiEq0Ao/giphy.gif?cid=ecf05e47qz7gy92p8f18f5sj8zwdijxly4m4lv2h0d49gzt8&rid=giphy.gif&ct=g" />
        </div>
        <p className="text-center pt-5 text-[#123c69] ">
          Software Engineer at{" "}
          <span className="text-[#ac3b61] bg-[#d1e8e2] pt-1 pb-1 px-2 font-bold">
            PwC
          </span>
        </p>
      </div>
      {/* menu */}

      <div className="flex flex-col w-[200px] m-auto text-center  mt-5">
        <Link href="">
          <a
            onMouseEnter={() => setButtonState("")}
            onMouseLeave={() => setButtonState("hidden")}
            className="cursor-pointer mb-1.5 hover:bg-[#edc7b7] border-2 rounded-sm border-[#000] px-2 font-bold py-1"
          >
            <p>Skills</p>
          </a>
        </Link>{" "}
        <Link href="">
          <a className="cursor-pointer mb-1.5 hover:bg-[#edc7b7] px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            Projects
          </a>
        </Link>{" "}
        <Link href="">
          <a className="cursor-pointer mb-1.5 hover:bg-[#edc7b7] px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            Blogs
          </a>
        </Link>{" "}
        <Link href="">
          <a className="cursor-pointer mb-1.5 hover:bg-[#edc7b7] px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            Github
          </a>
        </Link>{" "}
        <Link href="">
          <a className="cursor-pointer mb-1.5 hover:bg-[#edc7b7] px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            Leetcode <span>130/2338</span>
          </a>
        </Link>{" "}
        <Link href="">
          <a className="cursor-pointer pb-1.5 mb-1.5 hover:bg-[#edc7b7] px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            About Me
          </a>
        </Link>
        <Link href="">
          <a className="cursor-pointer pb-1.5  bg-[#6dcfa1] hover:bg-[#15db95]  px-2 font-bold border-2 rounded-sm border-[#000] py-1">
            <div className="flex justify-center">
              <p>Resume</p>
              <ArrowCircleDownIcon className="w-5 pl-1 " />
            </div>
          </a>
        </Link>
      </div>
      {/* contactme */}
      <div className="">
        <h1 className="text-[24px] font-black text-[#123c69] text-center mt-8">
          Connect Me
        </h1>
        <div></div>
      </div>
    </div>
  );
}
